### ISSUE TITLE
ORB-SLAM2 16bit Implementation

### ISSUE THREAD

**Issue by jonathansel** [HyeonJaeGil/ORB16#1]
Hi @HyeonJaeGil 

Awesome work, thank you for open-sourcing!

Do you happen to have an implementation of ORB16 in ORBSLAM2/3 to test? If not, do you have any suggestions on how to go about implementing it? I may give it a shot. Thank you!

**Comment by HyeonJaeGil** [comment]
Hi, thanks for your interest in my work.

Integrating ORB16 into ORB SLAM2/3 would be quite annoying, since
- the whole pipeline of ORB SLAM utilizes their own verison of ORB detection/description, not OpenCV's.
- and my code is based on OpenCV's ORB implementation.

But I found it necessary to integrate them anyway,
so I'll try to make ORB SLAM compatible with 16-bit image as soon as possible.

Source code will be updated in the forked repo [here](https://github.com/HyeonJaeGil/ORB_SLAM3), so you may watch it to send you notification.

Thanks,
Hyeonjae Gil.

**Comment by jonathansel** [comment]
Hi, 

Great to hear, I will look out for updates on your forked repo. 

Thank you!
